"""DDL File Writer — generates reference DDL SQL files for dfe-schemas.

Produces standalone, runnable SQL files from schema YAML definitions.
QoL tool for devs and sysops who want to see actual ClickHouse table
structures without running the engine.

Usage:
    from dfe_engine.schema.ddl_writer import DDLFileWriter

    writer = DDLFileWriter()
    written = writer.write_all(Path("schemas/ddl"))
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from ..source.type_registry import TypeRegistry
from .schema_ddl import DDLConfig, DDLGenerator
from .schema_loader import SchemaLoader, _resolve_profiles_dir, _resolve_schemas_root

_PROFILES = ("timeseries", "minimal", "passthrough")


class DDLFileWriter:
    """Generates and writes reference DDL SQL files.

    Orchestrates SchemaLoader and DDLGenerator to produce standalone
    ``.sql`` files for each known table structure.
    """

    def __init__(self, registry: TypeRegistry | None = None) -> None:
        self._registry = registry or TypeRegistry.default()
        self._ddl_gen = DDLGenerator(self._registry)

    # ── Individual generators ────────────────────────────────────────

    def generate_default_table(self, profile: str = "timeseries") -> str:
        """Generate DDL for the default ingestion table (profile columns only)."""
        columns = SchemaLoader.load_profile(profile)
        config = DDLConfig(
            db="{db}",
            profile=profile,
            profile_version=self._profile_version(profile),
        )
        ddl = self._ddl_gen.generate_create_table("default", columns, config)
        return self._replace_header(
            ddl,
            self._metadata_header(
                name="dfe.default",
                profile=profile,
                description="Default ingestion table (profile columns only)",
            ),
        )

    def generate_profile_table(self, profile_name: str) -> str:
        """Generate DDL for a profile-only reference table."""
        columns = SchemaLoader.load_profile(profile_name)
        config = DDLConfig(
            db="{db}",
            profile=profile_name,
            profile_version=self._profile_version(profile_name),
        )
        table_name = f"_{profile_name}_profile"
        ddl = self._ddl_gen.generate_create_table(table_name, columns, config)
        return self._replace_header(
            ddl,
            self._metadata_header(
                name=f"Profile reference: {profile_name}",
                profile=profile_name,
                description=f"Reference DDL for the {profile_name} common header profile",
            ),
        )

    @staticmethod
    def generate_checkpoint_table() -> str:
        """Generate DDL for the hunt checkpoint table.

        Extracted from HuntCheckpointManager.ensure_table_exists().
        """
        return textwrap.dedent("""\
            -- =============================================================================
            -- DFE Schema DDL: dfe_audit.detection_checkpoint
            -- Purpose: Hunt execution checkpoint tracking
            -- Generated by: dfe-engine DDLFileWriter
            --
            -- This file is auto-generated. Use {db} as database placeholder.
            -- =============================================================================

            CREATE TABLE IF NOT EXISTS {db}.detection_checkpoint
            (
                customer_name LowCardinality(String) CODEC(LZ4),
                rule_name LowCardinality(String) CODEC(LZ4),
                thread_id LowCardinality(String) CODEC(LZ4),
                log_buffer UInt32 CODEC(Delta, ZSTD),
                query_schedule_time DateTime CODEC(DoubleDelta, LZ4),
                execution_time DateTime CODEC(DoubleDelta, LZ4),
                end_time DateTime CODEC(DoubleDelta, LZ4),
                previous_successful_checkpoint DateTime CODEC(DoubleDelta, LZ4),
                query_checkpoint_time DateTime CODEC(DoubleDelta, LZ4),
                execution_time_ms Int32 CODEC(Delta, ZSTD),
                hunt_name LowCardinality(String) CODEC(LZ4),
                query_id LowCardinality(String) CODEC(LZ4),
                explain_plan String DEFAULT '' CODEC(ZSTD),
                explain_duration_ms Int32 DEFAULT 0 CODEC(Delta, ZSTD),
                scheduling_mode LowCardinality(String) DEFAULT 'adaptive' CODEC(LZ4),
                read_rows UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
                read_bytes UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
                memory_usage UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
                result_rows UInt64 DEFAULT 0 CODEC(Delta, ZSTD),
                query_fingerprint LowCardinality(String) DEFAULT '' CODEC(LZ4)
            ) ENGINE = MergeTree()
            PARTITION BY toYYYYMM(query_checkpoint_time)
            ORDER BY (customer_name, hunt_name, rule_name, query_checkpoint_time);
        """)

    def generate_hunt_results_table(self, profile: str = "timeseries") -> str:
        """Generate DDL for the hunt results table.

        Composes filtered profile columns (no _raw, _tags) with detection
        columns from hunt-results/detection.yaml.
        """
        profile_cols = SchemaLoader.load_profile(profile)
        filtered = [c for c in profile_cols if c.name not in ("_raw", "_tags")]

        detection_path = self._resolve_hunt_results_path()
        detection_cols = SchemaLoader.load_columns(detection_path)

        all_columns = SchemaLoader.compose(filtered, detection_cols)

        config = DDLConfig(
            db="{db}",
            profile=profile,
            profile_version=self._profile_version(profile),
            ttl_days=365,
        )
        ddl = self._ddl_gen.generate_create_table("detection", all_columns, config)
        return self._replace_header(
            ddl,
            self._metadata_header(
                name="dfe_hunts.detection",
                profile=profile,
                description="Hunt detection results (profile + detection columns)",
            ),
        )

    # ── Batch generators ─────────────────────────────────────────────

    def generate_all(self) -> dict[str, str]:
        """Generate all DDL files as a dict of {relative_path: sql_content}."""
        files: dict[str, str] = {}

        files["dfe.default.sql"] = self.generate_default_table()
        files["dfe_audit.detection_checkpoint.sql"] = self.generate_checkpoint_table()
        files["dfe_hunts.detection.sql"] = self.generate_hunt_results_table()

        for profile in _PROFILES:
            files[f"profiles/{profile}.sql"] = self.generate_profile_table(profile)

        return files

    def write_all(self, output_dir: str | Path) -> list[Path]:
        """Write all DDL files to the output directory.

        Creates directories as needed. Returns list of paths written.
        """
        output_dir = Path(output_dir)
        written: list[Path] = []

        for rel_path, sql in sorted(self.generate_all().items()):
            full_path = output_dir / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(sql)
            written.append(full_path)

        return written

    # ── Private helpers ──────────────────────────────────────────────

    @staticmethod
    def _metadata_header(
        *,
        name: str,
        profile: str,
        description: str,
    ) -> str:
        """Build the static metadata header block for a DDL file."""
        return (
            f"-- =============================================================================\n"
            f"-- DFE Schema DDL: {name}\n"
            f"-- Profile: {profile}\n"
            f"-- {description}\n"
            f"-- Generated by: dfe-engine DDLFileWriter\n"
            f"--\n"
            f"-- This file is auto-generated. Use {{db}} as database placeholder.\n"
            f"-- ============================================================================="
        )

    @staticmethod
    def _replace_header(ddl: str, new_header: str) -> str:
        """Replace the timestamp header line with a static metadata block."""
        lines = ddl.split("\n", 1)
        if len(lines) < 2 or not lines[0].startswith("-- HyperI DFE"):
            return new_header + "\n" + ddl
        return new_header + "\n" + lines[1]

    @staticmethod
    def _profile_version(profile_name: str) -> str:
        """Get the current version of a profile from its YAML metadata."""
        try:
            profile_path = _resolve_profiles_dir() / f"{profile_name}.yaml"
            meta = SchemaLoader.load_version_metadata(profile_path)
            return meta.get("current", "1.0.0")
        except Exception:
            return "1.0.0"

    @staticmethod
    def _resolve_hunt_results_path() -> Path:
        """Resolve the path to hunt-results/detection.yaml."""
        schemas_root = _resolve_schemas_root()
        if schemas_root:
            candidate = schemas_root / "hunt-results" / "detection.yaml"
            if candidate.exists():
                return candidate
        # Bundled fallback — shouldn't normally be needed
        raise FileNotFoundError(
            "hunt-results/detection.yaml not found in schemas directory. "
            "Ensure the dfe-schemas submodule is checked out."
        )
