"""Schema Builder v2 — Orchestrates schema YAML → DDL pipeline.

Replaces the dfe_package.yaml-based SchemaBuilder in schema_builder.py.
Accepts a Source model and produces DDL using the v2 schema pipeline:

    Source → SchemaLoader (YAML) → DDLGenerator (DDL)

Usage:
    from dfe_engine.schema.schema_builder_v2 import SchemaBuilderV2
    from dfe_engine.source.models import Source

    builder = SchemaBuilderV2()
    result = builder.build(source)
    print(result.create_table_ddl)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from hyperi_pylib.logger import logger

from dfe_engine.schema.schema_ddl import DDLConfig, DDLGenerator
from dfe_engine.schema.schema_loader import SchemaLoader, SchemaLoadError, resolve_schema_yaml_path
from dfe_engine.source.models import SchemaColumn, Source, SourceVersion
from dfe_engine.source.type_registry import TypeRegistry

if TYPE_CHECKING:
    from dfe_engine.fieldmap.registry import FieldMapRegistry


class SchemaBuildError(Exception):
    """Error during schema build."""


@dataclass
class SchemaBuildResult:
    """Result of a schema build operation.

    Attributes:
        view_ddls: Dict of standard → view DDL (e.g. {"sigma": "CREATE ...", "ecs": "CREATE ..."}).
            Generated by ViewGenerator when a FieldMapRegistry is available.
        sigma_view_ddl: Legacy field — Sigma view DDL from Source.sigma.custom_mappings.
            Populated by SchemaBuilderV2.build() for backward compatibility.
    """

    source_name: str
    columns: list[SchemaColumn]
    create_table_ddl: str
    sigma_view_ddl: str | None = None
    view_ddls: dict[str, str] = field(default_factory=dict)
    validation_errors: list[str] = field(default_factory=list)


class SchemaBuilderV2:
    """Orchestrates the schema v2 build pipeline.

    Given a Source model:
    1. Loads the common header profile (timeseries, minimal, passthrough)
    2. Loads source schema columns (meta_schema + derived + additional)
    3. Composes profile + source columns
    4. Validates against TypeRegistry
    5. Generates CREATE TABLE DDL
    6. Generates Sigma view DDL (if sigma config present)
    """

    def __init__(
        self,
        registry: TypeRegistry | None = None,
        *,
        schemas_base_dir: str | Path | None = None,
        use_legacy_indexes: bool = False,
        field_map_registry: FieldMapRegistry | None = None,
    ) -> None:
        """Initialize the schema builder.

        Args:
            registry: TypeRegistry for type resolution. Defaults to TypeRegistry.default().
            schemas_base_dir: Base directory for schema YAML files (meta_schema,
                              derived_schema, additional_fields). Schema file paths
                              in the Source model are resolved relative to this.
                              If None, paths must be absolute.
            use_legacy_indexes: Use tokenbf/ngrambf instead of GA text indexes.
            field_map_registry: Optional FieldMapRegistry for generating standard
                                views (sigma, ecs, cim). When provided and the source
                                declares mapping_standards, view DDLs are included
                                in the build result.
        """
        self._registry = registry or TypeRegistry.default()
        self._schemas_base_dir = Path(schemas_base_dir) if schemas_base_dir else None
        self._ddl_gen = DDLGenerator(self._registry, use_legacy_indexes=use_legacy_indexes)
        self._field_map_registry = field_map_registry

    # ── Main entry points ───────────────────────────────────────────

    def build(self, source: Source) -> SchemaBuildResult:
        """Build the complete schema for a Source (deployed version)."""
        return self.build_for_source_version(source, source_version=source.runtime_version_id())

    def build_for_source_version(
        self,
        source: Source,
        *,
        source_version: str | None = None,
    ) -> SchemaBuildResult:
        """Build schema DDL for a specific source version snapshot.

        Defaults to ``source.deployed_version`` when *source_version* is omitted.
        """
        version_id = source_version or source.runtime_version_id()
        if version_id not in source.versions:
            raise SchemaBuildError(
                f"Source version '{version_id}' is not defined for source '{source.source}'"
            )
        snap = source.versions[version_id]

        profile_columns = self._load_profile_for_snapshot(source.source, snap)
        source_columns = self._load_source_columns_for_snapshot(source.source, snap)
        columns = SchemaLoader.compose(profile_columns, source_columns)

        errors = SchemaLoader.validate_columns(columns, self._registry)
        if errors:
            for err in errors:
                logger.warning(f"Schema validation: {err}")

        ddl_config = self._build_ddl_config_for_snapshot(snap)
        create_ddl = self._ddl_gen.generate_create_table(
            source.table_name,
            columns,
            ddl_config,
            generated_time=datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
        )

        sigma_ddl = None
        if snap.sigma and snap.sigma.custom_mappings:
            sigma_ddl = self._ddl_gen.generate_sigma_view(
                source.table_name, snap.sigma.custom_mappings, ddl_config
            )

        view_ddls = self._generate_view_ddls(
            source,
            ddl_config,
            mapping_standards=snap.mapping_standards,
        )

        return SchemaBuildResult(
            source_name=source.source,
            columns=columns,
            create_table_ddl=create_ddl,
            sigma_view_ddl=sigma_ddl,
            view_ddls=view_ddls,
            validation_errors=errors,
        )

    def load_columns_for_source_version(
        self,
        source: Source,
        *,
        source_version: str | None = None,
    ) -> list[SchemaColumn]:
        """Load composed schema columns for a specific source version snapshot.

        Uses the version's ``header`` for the common profile and ``schema`` for
        meta/derived/additional YAML references (including ``meta_schema_version``).
        Defaults to ``source.deployed_version`` when *source_version* is omitted.
        """
        version_id = source_version or source.runtime_version_id()
        if version_id not in source.versions:
            raise SchemaBuildError(
                f"Source version '{version_id}' is not defined for source '{source.source}'"
            )
        snap = source.versions[version_id]
        profile_columns = self._load_profile_for_snapshot(source.source, snap)
        source_columns = self._load_source_columns_for_snapshot(source.source, snap)
        return SchemaLoader.compose(profile_columns, source_columns)

    @staticmethod
    def version_snapshot_has_schema_files(snap: SourceVersion) -> bool:
        """True when the snapshot references at least one schema YAML file."""
        cfg = snap.schema_config
        return bool(cfg.meta_schema or cfg.derived_schema or cfg.additional_fields)

    def build_ddl_only(
        self,
        columns: list[SchemaColumn],
        table_name: str,
        config: DDLConfig | None = None,
    ) -> str:
        """Generate DDL from pre-composed columns (skip Source loading).

        Useful when columns are already assembled (e.g. in tests).
        """
        return self._ddl_gen.generate_create_table(table_name, columns, config)

    def generate_alter_add(
        self,
        source: Source,
        column: SchemaColumn,
        *,
        after: str | None = None,
    ) -> str:
        """Generate ALTER TABLE ADD COLUMN for a Source."""
        cfg = self._build_ddl_config(source)
        return self._ddl_gen.generate_alter_add_column(source.table_name, column, cfg, after=after)

    def generate_alter_modify(
        self,
        source: Source,
        column: SchemaColumn,
    ) -> str:
        """Generate ALTER TABLE MODIFY COLUMN for a Source."""
        cfg = self._build_ddl_config(source)
        return self._ddl_gen.generate_alter_modify_column(source.table_name, column, cfg)

    # ── Internal: view generation ──────────────────────────────────

    def _generate_view_ddls(
        self,
        source: Source,
        config: DDLConfig,
        *,
        mapping_standards: list[str] | None = None,
    ) -> dict[str, str]:
        """Generate standard view DDLs from the FieldMapRegistry.

        Only runs when a field_map_registry was provided and the source
        declares mapping_standards.
        """
        standards = (
            list(mapping_standards)
            if mapping_standards is not None
            else list(source.mapping_standards)
        )
        if not self._field_map_registry or not standards:
            return {}

        from dfe_engine.fieldmap.view_generator import ViewGenerator

        view_gen = ViewGenerator(self._field_map_registry, self._registry)
        return view_gen.generate_views_for_source(
            source_name=source.source,
            table_name=source.table_name,
            standards=standards,
            config=config,
        )

    # ── Internal: loading ───────────────────────────────────────────

    def _load_profile(self, source: Source) -> list[SchemaColumn]:
        """Load the common header profile for the deployed source version."""
        return self._load_profile_for_snapshot(source.source, source.version())

    def _load_profile_for_snapshot(
        self, source_name: str, snap: SourceVersion
    ) -> list[SchemaColumn]:
        """Load the common header profile from a source version snapshot."""
        profile_name = snap.header.type
        profile_version = snap.header.version
        try:
            return SchemaLoader.load_profile(profile_name, profile_version=profile_version)
        except SchemaLoadError as e:
            raise SchemaBuildError(
                f"Failed to load profile {profile_name!r} for source {source_name!r}: {e}"
            ) from e

    def _load_source_columns(self, source: Source) -> list[SchemaColumn]:
        """Load source-specific schema columns for the deployed version."""
        return self._load_source_columns_for_snapshot(source.source, source.version())

    def _load_source_columns_for_snapshot(
        self, source_name: str, snap: SourceVersion
    ) -> list[SchemaColumn]:
        """Load meta/derived/additional columns from a source version snapshot."""
        schema_cfg = snap.schema_config
        columns: list[SchemaColumn] = []

        if schema_cfg.meta_schema:
            meta_path = self._resolve_path(schema_cfg.meta_schema)
            try:
                columns = SchemaLoader.load_columns(
                    meta_path, version=schema_cfg.meta_schema_version
                )
            except SchemaLoadError as e:
                raise SchemaBuildError(
                    f"Failed to load meta_schema for source {source_name!r}: {e}"
                ) from e

        if schema_cfg.derived_schema:
            derived_path = self._resolve_path(schema_cfg.derived_schema)
            columns = SchemaLoader.apply_derived_schema(columns, derived_path)

        if schema_cfg.additional_fields:
            additional_path = self._resolve_path(schema_cfg.additional_fields)
            columns = SchemaLoader.apply_additional_fields(columns, additional_path)

        return columns

    def _resolve_path(self, path_str: str) -> Path:
        """Resolve a schema file path (relative to schemas_base_dir or absolute)."""
        if self._schemas_base_dir:
            return resolve_schema_yaml_path(self._schemas_base_dir, path_str)
        return Path(path_str)

    # ── Internal: DDL config ────────────────────────────────────────

    def _build_ddl_config(self, source: Source) -> DDLConfig:
        """Build DDLConfig from the deployed source version."""
        return self._build_ddl_config_for_snapshot(source.version())

    def _build_ddl_config_for_snapshot(self, snap: SourceVersion) -> DDLConfig:
        """Build DDLConfig from a source version snapshot."""
        schema_cfg = snap.schema_config
        return DDLConfig(
            engine=schema_cfg.engine,
            ttl_days=schema_cfg.ttl_days,
            profile_name=snap.header.type,
            profile_version=snap.header.version,
        )
