"""Schema Builder v2 -- Orchestrates schema YAML -> DDL pipeline.

Replaces the dfe_package.yaml-based SchemaBuilder in schema_builder.py.
Accepts a Source model and produces DDL using the v2 schema pipeline:

    Source -> SchemaLoader (YAML) -> DDLGenerator (DDL)

Usage:
    from dfe_engine.schema.schema_builder_v2 import SchemaBuilderV2
    from dfe_engine.source.models import Source

    builder = SchemaBuilderV2()
    result = builder.build(source)
    print(result.create_table_ddl)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from scalo.logger import logger

from dfe_engine.schema.engine_resolver import EngineResolver
from dfe_engine.schema.schema_ddl import DDLConfig, DDLGenerator
from dfe_engine.schema.schema_loader import (
    SchemaLoader,
    SchemaLoadError,
    _profile_file_stem,
    resolve_schema_yaml_path,
)
from dfe_engine.source.models import (
    DEFAULT_HEADER_TYPE,
    DEFAULT_HEADER_VERSION,
    SchemaColumn,
    Source,
    SourceVersion,
    SourceView,
)
from dfe_engine.source.type_registry import TypeRegistry

if TYPE_CHECKING:
    from dfe_engine.fieldmap.registry import FieldMapRegistry


class SchemaBuildError(Exception):
    """Error during schema build."""


def _authored_header_profile(
    snap: SourceVersion,
    *,
    default_type: str = DEFAULT_HEADER_TYPE,
    default_version: str = DEFAULT_HEADER_VERSION,
) -> tuple[str, str] | None:
    """Return ``(type, version)`` when the snapshot names a real profile file.

    An omitted header is unauthored and inherits *default_type* / *default_version*,
    which are the compiled-in header unless the caller passes the admin's override.
    An authored empty type names no file and must not become ``.yaml``.
    """
    if snap.header is None:
        if _profile_file_stem(default_type) is None:
            return None
        return default_type, default_version
    raw = snap.header.type or ""
    if _profile_file_stem(raw) is None:
        return None
    return raw, snap.header.version


def inherited_builder_kwargs(settings: Any) -> dict[str, Any]:
    """Engine, TTL and header defaults a schema build should inherit from *settings*.

    Callers that build a source for deploy or preview pass this through. Retention
    reconcile does not: it would add the new header's columns to live tables.
    """
    ch = settings.clickhouse
    return {
        "default_engine": getattr(ch, "default_engine", "") or "MergeTree",
        "default_ttl_days": getattr(ch, "default_ttl_days", None),
        "default_header_type": getattr(ch, "default_header_type", "") or DEFAULT_HEADER_TYPE,
        "default_header_version": getattr(ch, "default_header_version", "")
        or DEFAULT_HEADER_VERSION,
    }


@dataclass
class SchemaBuildResult:
    """Result of a schema build operation.

    Attributes:
        view_ddls: Dict of standard -> view DDL (e.g. {"sigma": "CREATE ...", "ecs": "CREATE ..."}).
            Generated by ViewGenerator for the source's declared views; a sigma
            view built from inline custom_mappings also lands here under "sigma".
    """

    source_name: str
    columns: list[SchemaColumn]
    create_table_ddl: str
    view_ddls: dict[str, str] = field(default_factory=dict)
    validation_errors: list[str] = field(default_factory=list)


class SchemaBuilderV2:
    """Orchestrates the schema v2 build pipeline.

    Given a Source model:
    1. Loads the common header profile (timeseries, minimal, passthrough)
    2. Loads source schema columns (meta_schema + derived + additional)
    3. Composes profile + source columns
    4. Validates against TypeRegistry
    5. Generates CREATE TABLE DDL
    6. Generates naming-standard view DDLs for the source's declared views
    """

    def __init__(
        self,
        registry: TypeRegistry | None = None,
        *,
        schemas_base_dir: str | Path | None = None,
        derived_base_dir: str | Path | None = None,
        use_legacy_indexes: bool = False,
        field_map_registry: FieldMapRegistry | None = None,
        default_engine: str = "MergeTree",
        default_ttl_days: int | None = None,
        default_header_type: str = DEFAULT_HEADER_TYPE,
        default_header_version: str = DEFAULT_HEADER_VERSION,
        resolver: EngineResolver | None = None,
    ) -> None:
        """Initialize the schema builder.

        Args:
            registry: TypeRegistry for type resolution. Defaults to TypeRegistry.default().
            schemas_base_dir: Base directory for schema YAML files (meta_schema,
                              derived_schema, additional_fields). Schema file paths
                              in the Source model are resolved relative to this.
                              If None, paths must be absolute.
            derived_base_dir: Root a ``derived/...`` reference resolves under. A
                              deployment with gitops stores derived schemas in the
                              deploy repo rather than the schemas tree, so the two
                              roots differ; pass
                              ``DerivedSchemaRegistry.reference_root``. None keeps
                              them in the schemas tree.
            use_legacy_indexes: Use tokenbf/ngrambf instead of GA text indexes.
            field_map_registry: Optional FieldMapRegistry for generating standard
                                views (sigma, ecs, cim, ocsf). When provided and the
                                source declares views, view DDLs are included
                                in the build result.
            default_engine: MergeTree-family engine used for tables whose source
                                schema leaves ``engine`` empty (the inherit sentinel).
                                Pass the deployment value
                                (``settings.clickhouse.default_engine``) so an
                                operator can make e.g. ReplacingMergeTree the default;
                                falls back to plain MergeTree.
            default_ttl_days: Retention for a source whose schema leaves ``ttl_days``
                                unset. Pass the deployment value
                                (``settings.clickhouse.default_ttl_days``); 0 declares
                                no TTL, which removes a live one, and None leaves it alone.
            default_header_type: Common-header profile an unauthored source inherits.
            default_header_version: Version of that profile.
            resolver: Engine resolver for the table engine and ``ON CLUSTER``. A
                                path that applies DDL to a live server passes one
                                built with that server's client, so a multi-node
                                cluster gets a Replicated table on every replica;
                                without one the DDL follows the deployment's
                                ``clickhouse.topology`` alone.
        """
        self._registry = registry or TypeRegistry.default()
        self._schemas_base_dir = Path(schemas_base_dir) if schemas_base_dir else None
        self._derived_base_dir = Path(derived_base_dir) if derived_base_dir else None
        self._ddl_gen = DDLGenerator(
            self._registry, use_legacy_indexes=use_legacy_indexes, resolver=resolver
        )
        self._field_map_registry = field_map_registry
        self._default_engine = default_engine or "MergeTree"
        self._default_ttl_days = default_ttl_days
        self._default_header_type = default_header_type or DEFAULT_HEADER_TYPE
        self._default_header_version = default_header_version or DEFAULT_HEADER_VERSION

    # -- Main entry points -------------------------------------------

    def build(self, source: Source) -> SchemaBuildResult:
        """Build the complete schema for a Source (deployed version)."""
        return self.build_for_source_version(source, source_version=source.runtime_version_id())

    def build_for_source_version(
        self,
        source: Source,
        *,
        source_version: str | None = None,
    ) -> SchemaBuildResult:
        """Build schema DDL for a specific source version snapshot.

        Defaults to ``source.deployed_version`` when *source_version* is omitted.
        """
        version_id = source_version or source.runtime_version_id()
        if version_id not in source.versions:
            raise SchemaBuildError(
                f"Source version '{version_id}' is not defined for source '{source.source}'"
            )
        snap = source.versions[version_id]

        profile_columns = self._load_profile_for_snapshot(source.source, snap)
        source_columns = self._load_source_columns_for_snapshot(source.source, snap)
        columns = SchemaLoader.compose(profile_columns, source_columns)

        errors = SchemaLoader.validate_columns(columns, self._registry)
        if errors:
            for err in errors:
                logger.warning(f"Schema validation: {err}")

        ddl_config = self._build_ddl_config_for_snapshot(snap)
        create_ddl = self._ddl_gen.generate_create_table(
            source.table_name,
            columns,
            ddl_config,
            generated_time=datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S UTC"),
        )

        view_ddls = self._generate_view_ddls(source, ddl_config, views=snap.views)

        return SchemaBuildResult(
            source_name=source.source,
            columns=columns,
            create_table_ddl=create_ddl,
            view_ddls=view_ddls,
            validation_errors=errors,
        )

    def load_columns_for_source_version(
        self,
        source: Source,
        *,
        source_version: str | None = None,
    ) -> list[SchemaColumn]:
        """Load composed schema columns for a specific source version snapshot.

        Uses the version's ``header`` for the common profile and ``schema`` for
        meta/derived/additional YAML references (including ``meta_schema_version``).
        Defaults to ``source.deployed_version`` when *source_version* is omitted.
        """
        version_id = source_version or source.runtime_version_id()
        if version_id not in source.versions:
            raise SchemaBuildError(
                f"Source version '{version_id}' is not defined for source '{source.source}'"
            )
        snap = source.versions[version_id]
        profile_columns = self._load_profile_for_snapshot(source.source, snap)
        source_columns = self._load_source_columns_for_snapshot(source.source, snap)
        return SchemaLoader.compose(profile_columns, source_columns)

    @staticmethod
    def version_snapshot_has_schema_files(snap: SourceVersion) -> bool:
        """True when the snapshot references at least one schema YAML file."""
        cfg = snap.effective_schema()
        return bool(cfg.meta_schema or cfg.derived_schema or cfg.additional_fields)

    def build_ddl_only(
        self,
        columns: list[SchemaColumn],
        table_name: str,
        config: DDLConfig | None = None,
    ) -> str:
        """Generate DDL from pre-composed columns (skip Source loading).

        Useful when columns are already assembled (e.g. in tests).
        """
        return self._ddl_gen.generate_create_table(table_name, columns, config)

    def generate_alter_add(
        self,
        source: Source,
        column: SchemaColumn,
        *,
        after: str | None = None,
    ) -> str:
        """Generate ALTER TABLE ADD COLUMN for a Source."""
        cfg = self._build_ddl_config(source)
        return self._ddl_gen.generate_alter_add_column(source.table_name, column, cfg, after=after)

    def generate_alter_modify(
        self,
        source: Source,
        column: SchemaColumn,
    ) -> str:
        """Generate ALTER TABLE MODIFY COLUMN for a Source."""
        cfg = self._build_ddl_config(source)
        return self._ddl_gen.generate_alter_modify_column(source.table_name, column, cfg)

    def build_ddl_config_for_version(self, source: Source, version_id: str) -> DDLConfig:
        """DDL config for a specific source version snapshot."""
        if version_id not in source.versions:
            raise SchemaBuildError(
                f"Source version '{version_id}' is not defined for source '{source.source}'"
            )
        return self._build_ddl_config_for_snapshot(source.versions[version_id])

    # -- Internal: view generation ----------------------------------

    def _generate_view_ddls(
        self,
        source: Source,
        config: DDLConfig,
        *,
        views: list[SourceView] | None = None,
    ) -> dict[str, str]:
        """Generate standard view DDLs for the source's declared views.

        The FieldMapRegistry two-tier resolution is the base: a view's
        ``field_map`` pin replaces the source-name convention for the
        registry override layer, and its inline ``custom_mappings`` then WIN
        per-key over the registry result (locked precedence) - such a view
        renders even without a registry. Views with neither go through the
        ViewGenerator (interface unchanged); each view renders exactly once.
        """
        declared = list(views) if views is not None else list(source.views)
        if not declared:
            return {}

        # A view the overlay loop below renders (a field_map pin or inline
        # mappings) is excluded from the ViewGenerator pass - one render per
        # view, no double work.
        plain = [v for v in declared if not (v.custom_mappings or v.field_map)]

        view_ddls: dict[str, str] = {}
        if self._field_map_registry and plain:
            from dfe_engine.fieldmap.view_generator import ViewGenerator

            view_gen = ViewGenerator(self._field_map_registry, self._registry)
            view_ddls = view_gen.generate_views_for_source(
                source_name=source.source,
                table_name=source.table_name,
                standards=[v.standard for v in plain],
                config=config,
            )

        # Inline-wins overlay: merge registry base (honouring a field_map pin)
        # + per-view custom_mappings.
        from dfe_engine.fieldmap.resolver import resolve_registry_mappings

        for view in declared:
            if not (view.custom_mappings or view.field_map):
                continue
            mappings: dict[str, str] = {}
            if self._field_map_registry:
                mappings.update(
                    resolve_registry_mappings(
                        self._field_map_registry,
                        view.standard,
                        source.source,
                        field_map=view.field_map,
                    )
                )
            mappings.update(view.custom_mappings)
            if not mappings:
                # A pin-only view whose maps are absent: same skip the
                # ViewGenerator applies to a standard with no maps.
                continue
            view_ddls[view.standard] = self._ddl_gen.generate_view(
                source.table_name, mappings, view.standard, config
            )

        return view_ddls

    # -- Internal: loading -------------------------------------------

    def _load_profile(self, source: Source) -> list[SchemaColumn]:
        """Load the common header profile for the deployed source version."""
        return self._load_profile_for_snapshot(source.source, source.version())

    def _load_profile_for_snapshot(
        self, source_name: str, snap: SourceVersion
    ) -> list[SchemaColumn]:
        """Load the common header profile from a source version snapshot."""
        # The same derivation _build_ddl_config_for_snapshot uses, so the columns
        # loaded are the ones the DDL config declares a profile and a TTL over.
        profile_ref = _authored_header_profile(
            snap,
            default_type=self._default_header_type,
            default_version=self._default_header_version,
        )
        if profile_ref is None:
            return []
        profile_name, profile_version = profile_ref
        try:
            return SchemaLoader.load_profile(profile_name, profile_version=profile_version)
        except SchemaLoadError as e:
            raise SchemaBuildError(
                f"Failed to load profile {profile_name!r} for source {source_name!r}: {e}"
            ) from e

    def _load_source_columns(self, source: Source) -> list[SchemaColumn]:
        """Load source-specific schema columns for the deployed version."""
        return self._load_source_columns_for_snapshot(source.source, source.version())

    def _load_source_columns_for_snapshot(
        self, source_name: str, snap: SourceVersion
    ) -> list[SchemaColumn]:
        """Load meta/derived/additional columns from a source version snapshot."""
        schema_cfg = snap.effective_schema()
        columns: list[SchemaColumn] = []

        if schema_cfg.meta_schema:
            meta_path = self._resolve_path(schema_cfg.meta_schema)
            try:
                columns = SchemaLoader.load_columns(
                    meta_path, version=schema_cfg.meta_schema_version
                )
            except SchemaLoadError as e:
                raise SchemaBuildError(
                    f"Failed to load meta_schema for source {source_name!r}: {e}"
                ) from e

        if schema_cfg.derived_schema:
            derived_path = self.resolve_derived_path(schema_cfg.derived_schema)
            columns = SchemaLoader.apply_derived_schema(
                columns, derived_path, version=schema_cfg.derived_schema_version
            )

        if schema_cfg.additional_fields:
            additional_path = self._resolve_path(schema_cfg.additional_fields)
            columns = SchemaLoader.apply_additional_fields(columns, additional_path)

        return columns

    def _resolve_path(self, path_str: str) -> Path:
        """Resolve a schema file path (relative to schemas_base_dir or absolute)."""
        if self._schemas_base_dir:
            return resolve_schema_yaml_path(self._schemas_base_dir, path_str)
        return Path(path_str)

    def resolve_derived_path(self, path_str: str) -> Path:
        """Resolve a ``derived/...`` reference under its own root, then the schemas tree.

        The derived-schema store is the deploy repo when gitops is on, so the
        reference is looked for there first; a derived schema the release ships
        and the store does not hold resolves under the schemas tree.
        """
        from dfe_engine.schema.derived_registry import resolve_derived_reference

        return resolve_derived_reference(path_str, self._derived_base_dir, self._schemas_base_dir)

    # -- Internal: DDL config ----------------------------------------

    def _build_ddl_config(self, source: Source) -> DDLConfig:
        """Build DDLConfig from the deployed source version."""
        return self._build_ddl_config_for_snapshot(source.version())

    def _build_ddl_config_for_snapshot(self, snap: SourceVersion) -> DDLConfig:
        """Build DDLConfig from a source version snapshot."""
        schema_cfg = snap.effective_schema()
        authored = _authored_header_profile(
            snap,
            default_type=self._default_header_type,
            default_version=self._default_header_version,
        )
        # Empty engine or unset ttl_days = inherit the deployment default; a per-source pin wins.
        return DDLConfig(
            engine=schema_cfg.engine or self._default_engine,
            ttl_days=schema_cfg.ttl_days
            if schema_cfg.ttl_days is not None
            else self._default_ttl_days,
            profile_name=authored[0] if authored else None,
            profile_version=authored[1] if authored else None,
        )
