import os
import shutil
import pytest
import yaml
import pandas as pd
import logging
from pathlib import Path
from dfecli.dfe_config.config_loader import DFEConfigLoader
from dfecli.dfe_clickhouse.clickhouse_manager import ClickHouseManager


def _create_base_meta_schema_alerts():
    """Create a base meta schema DataFrame for alerts that can be customized per test."""
    return pd.DataFrame(
        {
            "column": [
                "alert_uid",
                "tags_str",
                "_source_event_hash",
                "_source",
                "alert_name",
                "alert_severity",
                "alert_type",
                "confidence_level",
                "condidence_score",
                "detection_time",
                "event_id",
                "event",
                "remediation_steps",
                "rule_id",
                "source_table",
                "tactics",
                "techniques",
            ],
            "type": [
                "string_fast",
                "string_fast",
                "string_fast",
                "string_fast_lowcardinality",
                "string_fast",
                "string_fast",
                "string_fast",
                "string_fast_lowcardinality",
                "int16",
                "timestamp",
                "string_fast",
                "text",
                "string_fast",
                "uuid",
                "string_fast_lowcardinality",
                "string_fast",
                "string_fast",
            ],
            "index_order": [""] * 17,
            "os_order": [""] * 17,
            "comment": [
                "Generate UUID for this specific alert that has occurred",
                "keywords that describe the event",
                "Extracted copy of event that triggered alert",
                "Add Rule Name",
                "Name of the alert / Display Name",
                "enum Unassigned / Informational / Low / Medium / High / Critical",
                "scheduled alert / adhoc alert",
                "likelihood this is a real alert vs false positive",
                "int representation of above",
                "Time alert was generated by our detection system",
                "Original event ID",
                "Original event as JSON event string",
                "Triggers for soar",
                "UUID of rule which triggered alert",
                "source table the alert was generated from",
                "comma sep list of mtire att&ck tactics",
                "comma sep list of mtire att&ck techniques",
            ],
        }
    )


def _create_base_meta_schema_nxlog_windows():
    """Create a base meta schema DataFrame for nxlog windows that can be customized per test."""
    columns = [
        "event_id",
        "domain",
        "event_creation_time",
        "category",
        "channel",
        "description",
        "event_type",
        "hostname",
        "ip_address",
        "level",
        "message",
        "process_id",
        "severity",
        "source_name",
        "subject_domain_name",
        "subject_user_name",
        "target_domain_name",
        "target_user_name",
    ]

    types = [
        "string",
        "string_fast_lowcardinality",
        "datetime",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "text",
        "string",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
        "string_fast_lowcardinality",
    ]

    index_orders = [
        "2",
        "",
        "",
        "0",
        "1",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    index_types = [""] * len(columns)
    os_orders = [""] * len(columns)
    comments = [
        "Windows Event Log ID",
        "Domain",
        "Event Creation Time",
        "Category",
        "Channel",
        "Description",
        "Event Type",
        "Hostname",
        "IP Address",
        "Level",
        "Message",
        "Process ID",
        "Severity",
        "Source Name",
        "Subject Domain Name",
        "Subject Username",
        "Target Domain Name",
        "Target Username",
    ]

    return pd.DataFrame(
        {
            "column": columns,
            "type": types,
            "index_order": index_orders,
            "index_type": index_types,
            "os_order": os_orders,
            "comment": comments,
        }
    )


def _create_base_meta_schema_filebeat():
    """Create a base meta schema DataFrame for filebeat that can be customized per test."""
    return pd.DataFrame(
        {
            "column": ["user*", "agent_properties_id", "o365.audit.Severity"],
            "type": [
                "string_fast_lowcardinality",
                "string_fast_lowcardinality",
                "string_fast_lowcardinality",
            ],
            "index_order": ["", "", ""],
            "os_order": ["", "", ""],
            "comment": ["User fields", "Agent ID", "Severity"],
        }
    )


@pytest.fixture
def create_base_meta_schema_alerts():
    return _create_base_meta_schema_alerts()


@pytest.fixture
def create_base_meta_schema_nxlog_windows():
    return _create_base_meta_schema_nxlog_windows()


@pytest.fixture
def create_base_meta_schema_filebeat():
    return _create_base_meta_schema_filebeat()


@pytest.fixture(scope="session")
def dfe_config_fixtures(tmp_path_factory):
    """Create test configuration with proper paths."""
    temp_dir = tmp_path_factory.mktemp("test_dfe_schema_output")
    targets_dir = tmp_path_factory.mktemp("test_targets")
    targets_path = targets_dir / "dfe_targets.yaml"

    targets_data = {
        "default_target": "test_schemas",
        "targets": {
            "test_schemas": {
                "ch_host": "localhost",
                "ch_port": 8123,
                "ch_database": "default",
            }
        },
    }

    with open(targets_path, "w") as f:
        yaml.dump(targets_data, f)

    post_build_path = (
        Path(__file__).parent.parent.parent / "resources" / "post_build_artefacts"
    )

    config_data = {
        "global_settings": {
            "schema_common_version": "v001.001.007",
            "schema_output_path": str(temp_dir),
            "default_target": "test_schemas",
            "target_path": str(targets_path),
            "use_json_feature": False,
            "use_subsampling_feature": False,
            "vector_files": {
                "standard": [
                    "ingestion_pipeline_enrichment_standard",
                    "ingestion_pipeline_enrichment_standard_custom",
                ],
                "geoip": ["ingestion_pipeline_enrichment_geoip"],
            },
            "vector_files": {
                "vector": ["ingestion_pipeline_templates"]
            },
            "derived_schema_paths": "tests/resources/test_schemas/stable_schemas",
            "meta_schema_paths": str(post_build_path / "dfe_meta_schemas"),
        },
        "build_schemas": {
            "no_cluster_declarations_needed": True,
            "use_replicated_merge_tree": False,
            "use_shared_merge_tree": False,
        },
        "apply_schemas": {
            "do_add_roles": True,
            "do_add_columns": True,
        },
        "organisations": [
            {"org_id": "detectionlab", "cluster_name": ""},
            {"org_id": "org321", "cluster_name": ""},
            {"org_id": "org111111", "cluster_name": ""},
        ],
        "schemas": {
            "logs_alerts": {
                "name": "logs_alerts",
                "meta_schema": "logs_alerts.csv",
                "meta_schema_version": "v001.000.000",
                "derived_schema_ttl": 90,
            },
            "nx_log_windows_sub_ce": {
                "name": "nx_log_windows_sub_ce",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "nx_log_windows_sub_ce/nx_log_windows_sub_ce.csv",
                "additional_fields_config": "nx_log_windows_sub_ce/nx_log_windows_ce_add_fields.csv",
                "unified_schema_mapping": "nx_log_windows_sub_ce/unified_schema_mapping.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest_sub": {
                "name": "log_windows_unittest_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest_sub/log_windows_unittest_sub.csv",
                "additional_fields_config": "log_windows_unittest_sub/log_windows_unittest_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest1_sub": {
                "name": "log_windows_unittest1_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest1_sub/log_windows_unittest1_sub.csv",
                "additional_fields_config": "log_windows_unittest1_sub/log_windows_unittest1_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest2_sub": {
                "name": "log_windows_unittest2_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest2_sub/log_windows_unittest2_sub.csv",
                "additional_fields_config": "log_windows_unittest2_sub/log_windows_unittest2_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "logs_nxlog_windows": {
                "name": "logs_nxlog_windows",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "logs_nxlog_windows/logs_nxlog_windows_sub.csv",
                "additional_fields_config": "logs_nxlog_windows/logs_nxlog_windows_add.csv",
                "derived_schema_ttl": 90,
            },
            "logs_beats_filebeat_igmp": {
                "name": "logs_beats_filebeat_igmp",
                "meta_schema": "logs_beats_filebeat.csv",
                "meta_schema_version": "v001.000.002",
                "derived_schema_file_path": "logs_beats_filebeat/logs_beats_filebeat_igmp.csv",
                "derived_schema_ttl": 90,
            },
            "logs_beats_winlogbeat": {
                "name": "logs_beats_winlogbeat",
                "meta_schema": "logs_beats_winlogbeat.csv",
                "meta_schema_version": "v001.000.000",
                "derived_schema_ttl": 90,
            },
        },
    }

    return config_data


@pytest.fixture(scope="session")
def dfe_config_fixtures_subsampling(tmp_path_factory):
    """Create test configuration with proper paths."""
    temp_dir = tmp_path_factory.mktemp("test_dfe_schema_output")
    targets_dir = tmp_path_factory.mktemp("test_targets")
    targets_path = targets_dir / "dfe_targets.yaml"

    targets_data = {
        "default_target": "test_schemas",
        "targets": {
            "test_schemas": {
                "ch_host": "localhost",
                "ch_port": 8123,
                "ch_database": "default",
            }
        },
    }

    with open(targets_path, "w") as f:
        yaml.dump(targets_data, f)

    post_build_path = (
        Path(__file__).parent.parent.parent / "resources" / "post_build_artefacts"
    )

    config_data = {
        "global_settings": {
            "schema_common_version": "v001.001.007",
            "schema_output_path": str(temp_dir),
            "default_target": "test_schemas",
            "target_path": str(targets_path),
            "use_json_feature": False,
            "use_subsampling_feature": True,
            "vector_files": {
                "standard": [
                    "ingestion_pipeline_enrichment_standard",
                    "ingestion_pipeline_enrichment_standard_custom",
                ],
                "geoip": ["ingestion_pipeline_enrichment_geoip"],
            },
            "vector_files": {
                "vector": ["ingestion_pipeline_templates"]
            },
            "derived_schema_paths": "tests/resources/test_schemas/stable_schemas",
            "meta_schema_paths": str(post_build_path / "dfe_meta_schemas"),
        },
        "build_schemas": {
            "no_cluster_declarations_needed": True,
            "use_replicated_merge_tree": False,
            "use_shared_merge_tree": False,
        },
        "apply_schemas": {
            "do_add_roles": True,
            "do_add_columns": True,
        },
        "organisations": [
            {"org_id": "detectionlab", "cluster_name": ""},
            {"org_id": "org321", "cluster_name": ""},
            {"org_id": "org111111", "cluster_name": ""},
        ],
        "schemas": {
            "logs_alerts": {
                "name": "logs_alerts",
                "meta_schema": "logs_alerts.csv",
                "meta_schema_version": "v001.000.000",
            },
            "nx_log_windows_sub_ce": {
                "name": "nx_log_windows_sub_ce",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "nx_log_windows_sub_ce/nx_log_windows_sub_ce.csv",
                "additional_fields_config": "nx_log_windows_sub_ce/nx_log_windows_ce_add_fields.csv",
                "unified_schema_mapping": "nx_log_windows_sub_ce/unified_schema_mapping.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest_sub": {
                "name": "log_windows_unittest_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest_sub/log_windows_unittest_sub.csv",
                "additional_fields_config": "log_windows_unittest_sub/log_windows_unittest_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest1_sub": {
                "name": "log_windows_unittest1_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest1_sub/log_windows_unittest1_sub.csv",
                "additional_fields_config": "log_windows_unittest1_sub/log_windows_unittest1_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest2_sub": {
                "name": "log_windows_unittest2_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest2_sub/log_windows_unittest2_sub.csv",
                "additional_fields_config": "log_windows_unittest2_sub/log_windows_unittest2_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "logs_nxlog_windows": {
                "name": "logs_nxlog_windows",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "logs_nxlog_windows/logs_nxlog_windows_sub.csv",
                "additional_fields_config": "logs_nxlog_windows/logs_nxlog_windows_add.csv",
                "derived_schema_ttl": 90,
            },
            "logs_beats_filebeat_igmp": {
                "name": "logs_beats_filebeat_igmp",
                "meta_schema": "logs_beats_filebeat.csv",
                "meta_schema_version": "v001.000.002",
                "derived_schema_file_path": "logs_beats_filebeat/logs_beats_filebeat_igmp.csv",
                "derived_schema_ttl": 90,
            },
            "logs_beats_winlogbeat": {
                "name": "logs_beats_winlogbeat",
                "meta_schema": "logs_beats_winlogbeat.csv",
                "meta_schema_version": "v001.000.000",
                "derived_schema_ttl": 90,
            },
        },
    }

    return config_data


@pytest.fixture(scope="session")
def dfe_config_fixtures_backward_compatibility(tmp_path_factory):
    """Create test configuration with proper paths."""
    temp_dir = tmp_path_factory.mktemp("test_dfe_schema_output")
    targets_dir = tmp_path_factory.mktemp("test_targets")
    targets_path = targets_dir / "dfe_targets.yaml"

    targets_data = {
        "default_target": "test_schemas",
        "targets": {
            "test_schemas": {
                "ch_host": "localhost",
                "ch_port": 8123,
                "ch_database": "default",
            }
        },
    }

    with open(targets_path, "w") as f:
        yaml.dump(targets_data, f)

    post_build_path = (
        Path(__file__).parent.parent.parent / "resources" / "post_build_artefacts"
    )

    config_data = {
        "global_settings": {
            "schema_common_version": "v001.001.004",
            "schema_output_path": str(temp_dir),
            "default_target": "test_schemas",
            "target_path": str(targets_path),
            "use_json_feature": False,
            "vector_files": {
                "standard": [
                    "ingestion_pipeline_enrichment_standard",
                    "ingestion_pipeline_enrichment_standard_custom",
                ],
                "geoip": ["ingestion_pipeline_enrichment_geoip"],
            },
            "vector_files": {
                "vector": ["ingestion_pipeline_templates"]
            },
            "derived_schema_paths": "tests/resources/test_schemas/stable_schemas",
            "meta_schema_paths": str(post_build_path / "dfe_meta_schemas"),
        },
        "build_schemas": {
            "no_cluster_declarations_needed": True,
            "use_replicated_merge_tree": False,
            "use_shared_merge_tree": False,
        },
        "apply_schemas": {
            "do_add_roles": True,
            "do_add_columns": True,
        },
        "organisations": [
            {"org_id": "detectionlab", "cluster_name": ""},
            {"org_id": "org321", "cluster_name": ""},
            {"org_id": "org111111", "cluster_name": ""},
        ],
        "schemas": {
            "logs_alerts": {
                "name": "logs_alerts",
                "meta_schema": "logs_alerts.csv",
                "meta_schema_version": "v001.000.000",
            },
            "nx_log_windows_sub_ce": {
                "name": "nx_log_windows_sub_ce",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "nx_log_windows_sub_ce/nx_log_windows_sub_ce.csv",
                "additional_fields_config": "nx_log_windows_sub_ce/nx_log_windows_ce_add_fields.csv",
                "unified_schema_mapping": "nx_log_windows_sub_ce/unified_schema_mapping.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest_sub": {
                "name": "log_windows_unittest_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest_sub/log_windows_unittest_sub.csv",
                "additional_fields_config": "log_windows_unittest_sub/log_windows_unittest_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest1_sub": {
                "name": "log_windows_unittest1_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest1_sub/log_windows_unittest1_sub.csv",
                "additional_fields_config": "log_windows_unittest1_sub/log_windows_unittest1_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "log_windows_unittest2_sub": {
                "name": "log_windows_unittest2_sub",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "log_windows_unittest2_sub/log_windows_unittest2_sub.csv",
                "additional_fields_config": "log_windows_unittest2_sub/log_windows_unittest2_add_fields.csv",
                "derived_schema_ttl": 90,
            },
            "logs_nxlog_windows": {
                "name": "logs_nxlog_windows",
                "meta_schema": "logs_nxlog_windows.csv",
                "meta_schema_version": "v001.000.004",
                "derived_schema_file_path": "logs_nxlog_windows/logs_nxlog_windows_sub.csv",
                "additional_fields_config": "logs_nxlog_windows/logs_nxlog_windows_add.csv",
                "derived_schema_ttl": 90,
            },
            "logs_beats_filebeat_igmp": {
                "name": "logs_beats_filebeat_igmp",
                "meta_schema": "logs_beats_filebeat.csv",
                "meta_schema_version": "v001.000.002",
                "derived_schema_file_path": "logs_beats_filebeat/logs_beats_filebeat_igmp.csv",
                "derived_schema_ttl": 90,
            },
            "logs_beats_winlogbeat": {
                "name": "logs_beats_winlogbeat",
                "meta_schema": "logs_beats_winlogbeat.csv",
                "meta_schema_version": "v001.000.000",
                "derived_schema_ttl": 90,
            },
        },
    }

    return config_data


logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)8s | %(module)20s:%(lineno)4d | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

test_stats = {"total": 0, "passed": 0, "failed": 0, "skipped": 0, "test_files": {}}


def pytest_runtest_logreport(report):
    """Collect test statistics."""
    if report.when == "call":
        test_stats["total"] += 1

        test_file = report.nodeid.split("::")[0]
        if test_file not in test_stats["test_files"]:
            test_stats["test_files"][test_file] = {
                "total": 0,
                "passed": 0,
                "failed": 0,
                "skipped": 0,
            }

        if report.passed:
            test_stats["passed"] += 1
            test_stats["test_files"][test_file]["passed"] += 1
        elif report.failed:
            test_stats["failed"] += 1
            test_stats["test_files"][test_file]["failed"] += 1
        elif report.skipped:
            test_stats["skipped"] += 1
            test_stats["test_files"][test_file]["skipped"] += 1

        test_stats["test_files"][test_file]["total"] += 1


def pytest_terminal_summary(terminalreporter, exitstatus):
    """Print test summary at the end."""
    logger.info(
        "\n===================== test_schemas Test Summary ====================="
    )
    logger.info("Overall Statistics:")
    logger.info(f"Total Tests Run: {test_stats['total']}")
    logger.info(f"Tests Passed:    {test_stats['passed']}")
    logger.info(f"Tests Failed:    {test_stats['failed']}")
    logger.info(f"Tests Skipped:   {test_stats['skipped']}")
    logger.info("\nBreakdown by Test File:")

    for test_file, stats in test_stats["test_files"].items():
        logger.info(f"\n{test_file}:")
        logger.info(f"  Total Tests: {stats['total']}")
        logger.info(f"  Passed:      {stats['passed']}")
        logger.info(f"  Failed:      {stats['failed']}")
        logger.info(f"  Skipped:     {stats['skipped']}")

    logger.info("=================================================================")


@pytest.fixture(scope="session")
def setup_paths(tmp_path_factory):
    """Create and clean up log paths."""
    dfe_root_log_path = tmp_path_factory.mktemp("logs_path")
    yield str(dfe_root_log_path)
    if os.path.exists(dfe_root_log_path):
        shutil.rmtree(dfe_root_log_path)


@pytest.fixture(scope="session")
def dfe_package(dfe_config_fixtures, tmp_path_factory):
    """Create and clean up test package file."""
    temp_dir = tmp_path_factory.mktemp("test_package")
    dfe_package_path = temp_dir / "dfe_package_testing.yaml"

    with open(dfe_package_path, "w") as f:
        yaml.dump(dfe_config_fixtures, f)

    yield str(dfe_package_path)
    if os.path.exists(dfe_package_path):
        os.remove(dfe_package_path)


@pytest.fixture
def target_config_data():
    """Mock target config data for unit tests."""
    return {"ch_host": "localhost", "ch_port": 8123}


@pytest.fixture(scope="module")
def ch_client(dfe_config_fixtures):
    """Create a ClickHouse client with retry mechanism."""
    config = DFEConfigLoader.read_clickhouse_config(
        target_name=dfe_config_fixtures["global_settings"]["default_target"],
        targets_file_path=dfe_config_fixtures["global_settings"]["target_path"],
    )
    print(f"*** using config {config}")

    ch_client = ClickHouseManager.get_instance(logger, config).get_clickhouse_client()

    yield ch_client


@pytest.fixture
def ensure_schema_db(ch_client):
    """Fixture to ensure database exists and handle retries for schema operations."""

    def _ensure_schema_db(org_name, operation_func):
        ch_client.execute(f"CREATE DATABASE IF NOT EXISTS {org_name}")
        max_retries = 3
        retry_delay = 10
        last_error = None

        for attempt in range(max_retries):
            try:
                result = operation_func()
                return result
            except Exception as e:
                last_error = e
                if attempt < max_retries - 1:
                    import time

                    time.sleep(retry_delay)
                    continue
                raise Exception(
                    f"Operation failed after {max_retries} attempts: {last_error}"
                )

    return _ensure_schema_db
