"""Tests for DDLFileWriter — reference DDL SQL file generation."""

import pytest

from dfe_engine.schema.ddl_writer import DDLFileWriter
from tests.unit.test_schema.conftest import requires_schemas


@pytest.fixture
def writer():
    return DDLFileWriter()


# ── Default Table ────────────────────────────────────────────────


class TestDefaultTable:
    """Test default ingestion table DDL generation."""

    def test_creates_valid_ddl(self, writer):
        ddl = writer.generate_default_table()
        assert "CREATE TABLE IF NOT EXISTS `{db}`.`main`" in ddl

    def test_uses_db_placeholder(self, writer):
        ddl = writer.generate_default_table()
        assert "{db}" in ddl

    def test_has_profile_columns(self, writer):
        ddl = writer.generate_default_table()
        assert "`_timestamp_load`" in ddl
        assert "`_timestamp`" in ddl
        assert "`_org_id`" in ddl
        assert "`_uuid`" in ddl

    def test_has_metadata_header(self, writer):
        ddl = writer.generate_default_table()
        assert "DFE Schema DDL: main" in ddl
        assert "Generated by: dfe-engine" in ddl
        assert "DDLFileWriter" in ddl

    def test_no_timestamp_in_header(self, writer):
        """Header should be static, not contain a runtime timestamp."""
        ddl = writer.generate_default_table()
        # The original DDLGenerator header starts with "-- HyperI DFE"
        # which we replace. Verify it's gone.
        first_line = ddl.split("\n")[0]
        assert "HyperI DFE" not in first_line

    def test_is_deterministic(self, writer):
        """Two calls produce identical output."""
        assert writer.generate_default_table() == writer.generate_default_table()

    def test_uses_mergetree(self, writer):
        ddl = writer.generate_default_table()
        assert "ENGINE = MergeTree()" in ddl


# ── Profile Tables ───────────────────────────────────────────────


class TestProfileTables:
    """Test profile-only reference DDL generation."""

    @pytest.mark.parametrize("profile", ["timeseries", "minimal", "passthrough"])
    def test_all_profiles_generate(self, writer, profile):
        ddl = writer.generate_profile_table(profile)
        assert "CREATE TABLE IF NOT EXISTS" in ddl
        assert "`_timestamp_load`" in ddl

    def test_timeseries_has_raw(self, writer):
        ddl = writer.generate_profile_table("timeseries")
        assert "`_raw`" in ddl

    def test_minimal_has_no_raw(self, writer):
        ddl = writer.generate_profile_table("minimal")
        assert "`_raw`" not in ddl

    def test_minimal_has_json(self, writer):
        ddl = writer.generate_profile_table("minimal")
        assert "`_json`" in ddl

    def test_passthrough_has_json(self, writer):
        ddl = writer.generate_profile_table("passthrough")
        assert "`_json`" in ddl


# ── Checkpoint Table ─────────────────────────────────────────────


@requires_schemas
class TestCheckpointTable:
    """Test detection checkpoint table DDL generation."""

    def test_structure(self, writer):
        ddl = writer.generate_detection_checkpoint_table()
        assert "detection_checkpoint" in ddl
        # Checkpoint rows are keyed by org/hunt/rule; customer_name was renamed
        # to _org_id in dfe-schemas#6.
        assert "_org_id" in ddl
        assert "customer_name" not in ddl
        assert "hunt_name" in ddl
        assert "rule_name" in ddl
        assert "query_checkpoint_time" in ddl

    def test_has_explain_columns(self, writer):
        ddl = writer.generate_detection_checkpoint_table()
        assert "explain_plan" in ddl
        assert "explain_duration_ms" in ddl
        assert "scheduling_mode" in ddl

    def test_uses_mergetree(self, writer):
        ddl = writer.generate_detection_checkpoint_table()
        assert "MergeTree()" in ddl

    def test_partitions_monthly(self, writer):
        # Low row count per day; daily partitions would accumulate a part per
        # day holding a handful of rows.
        ddl = writer.generate_detection_checkpoint_table()
        assert "PARTITION BY toYYYYMM(query_checkpoint_time)" in ddl

    def test_uses_db_placeholder(self, writer):
        ddl = writer.generate_detection_checkpoint_table()
        assert "{db}" in ddl

    def test_has_metadata_header(self, writer):
        ddl = writer.generate_detection_checkpoint_table()
        assert "DFE Schema DDL" in ddl


# ── Detection Table ──────────────────────────────────────────────


@requires_schemas
class TestDetectionTable:
    """Test hunt detection table DDL generation."""

    def test_has_profile_columns(self, writer):
        ddl = writer.generate_detection_table()
        assert "`_timestamp`" in ddl
        assert "`_org_id`" in ddl
        assert "`_uuid`" in ddl

    def test_has_detection_columns(self, writer):
        ddl = writer.generate_detection_table()
        assert "`matched_uuid`" in ddl
        assert "`rule_id`" in ddl
        assert "`rule_name`" in ddl
        assert "`source_table`" in ddl
        assert "`hunt_name`" in ddl
        assert "`severity`" in ddl

    def test_excludes_raw_and_tags(self, writer):
        # Honours hunts/results.yaml `profile_exclude` (#104, #127): a detection
        # references its source by matched_uuid, so a second copy of the payload
        # text and an ngram index over it earn nothing.
        ddl = writer.generate_detection_table()
        assert "`_raw`" not in ddl
        assert "`_tags`" not in ddl
        assert "idx__raw" not in ddl

    def test_uses_db_placeholder(self, writer):
        ddl = writer.generate_detection_table()
        assert "`{db}`.`detection`" in ddl

    def test_has_metadata_header(self, writer):
        ddl = writer.generate_detection_table()
        assert "DFE Schema DDL: detection" in ddl
        assert "Generated by: dfe-engine" in ddl


# ── target database ──────────────────────────────────────────────
# The default "{db}" placeholder is what the reference-SQL output wants (the
# caller substitutes it). A LIVE caller must pass the real name instead: the
# resolver senses by querying system.databases for that exact name, and "{db}"
# matches no row -- so a Replicated/Shared database reads back as None, falls
# past the Replicated branch, and a macro-configured server wrongly resolves to
# ON CLUSTER against a database that already replicates itself.


@requires_schemas
class TestTargetDatabase:
    def test_defaults_to_placeholder(self):
        # The static/reference path must keep emitting the placeholder.
        ddl = DDLFileWriter().generate_default_table()
        assert "CREATE TABLE IF NOT EXISTS `{db}`.`main`" in ddl

    def test_real_database_reaches_default_table_ddl(self):
        ddl = DDLFileWriter(database="dfe").generate_default_table()
        assert "CREATE TABLE IF NOT EXISTS `dfe`.`main`" in ddl
        assert "`{db}`.`main`" not in ddl

    def test_landing_table_name_reaches_the_ddl(self):
        # The name is env-driven (DFE_CLICKHOUSE_LANDING_TABLE); a live caller
        # passes the resolved setting, so the table this emits is the one the
        # query paths read.
        ddl = DDLFileWriter(database="dfe", landing_table="parked").generate_default_table()
        assert "CREATE TABLE IF NOT EXISTS `dfe`.`parked`" in ddl
        assert "`dfe`.`main`" not in ddl

    def test_real_database_reaches_detection_ddl(self):
        ddl = DDLFileWriter(database="dfe_hunts").generate_detection_table()
        assert "CREATE TABLE IF NOT EXISTS `dfe_hunts`.`detection`" in ddl
        assert "`{db}`.`detection`" not in ddl

    def test_real_database_reaches_checkpoint_ddl(self):
        ddl = DDLFileWriter(database="dfe").generate_detection_checkpoint_table()
        assert "CREATE TABLE IF NOT EXISTS `dfe`.`detection_checkpoint`" in ddl
        assert "`{db}`.`detection_checkpoint`" not in ddl


# ── generate_all ─────────────────────────────────────────────────
# generate_all() returns a NESTED tree keyed by table -> [profile ->] version ->
# filename, so the same table can be emitted per schema version and per profile.
# It is not the flat {filename: sql} map it once was.


def _leaves(tree, prefix=""):
    """Flatten the nested generate_all() tree to (path, sql) pairs."""
    for key, value in tree.items():
        path = f"{prefix}/{key}"
        if isinstance(value, dict):
            yield from _leaves(value, path)
        else:
            yield path, value


@requires_schemas
class TestGenerateAll:
    """Test batch generation."""

    def test_returns_expected_tables(self, writer):
        files = writer.generate_all()
        assert set(files) == {"main", "profiles", "detection_checkpoint", "detection"}

    def test_emits_every_profile(self, writer):
        files = writer.generate_all()
        assert set(files["profiles"]) == {"timeseries", "minimal", "passthrough"}
        assert set(files["main"]) == {"timeseries", "minimal", "passthrough"}

    def test_versioned_leaves(self, writer):
        paths = [p for p, _ in _leaves(writer.generate_all())]
        assert "/main/timeseries/1.0.0/main.sql" in paths
        assert "/profiles/minimal/1.0.0/minimal.sql" in paths
        assert "/detection_checkpoint/1.0.0/detection_checkpoint.sql" in paths
        assert "/detection/1.0.0/timeseries/1.0.0/detection.sql" in paths

    def test_all_values_are_sql_strings(self, writer):
        for path, content in _leaves(writer.generate_all()):
            assert isinstance(content, str), f"{path} is not a string"
            assert len(content) > 100, f"{path} content too short"
            assert path.endswith(".sql"), f"{path} doesn't end in .sql"


# ── write_all ────────────────────────────────────────────────────


@requires_schemas
class TestWriteAll:
    """Test file writing."""

    def test_creates_files(self, writer, tmp_path, monkeypatch):
        # Pin against the installed dfe-schemas package: a local DFE_SCHEMAS_DIR
        # (often from .env) can be an older partial tree and would under-count.
        monkeypatch.delenv("DFE_SCHEMAS_DIR", raising=False)
        written = writer.write_all(tmp_path / "ddl")
        # Pinned, not derived from generate_all(): deriving both sides would let a
        # regression that silently drops a profile pass. Every schema version is
        # emitted. The profiles carry 7 versions (timeseries 3, minimal 2,
        # passthrough 2), so 29 = main 7 + profiles 7 + detection_checkpoint 1 +
        # detection 2x7.
        assert len(written) == 29
        names = {p.relative_to(tmp_path / "ddl").as_posix() for p in written}
        # The detection table takes each profile's own versions, not the last profile's.
        assert "detection/1.0.1/timeseries/1.0.2/detection.sql" in names
        for p in written:
            assert p.exists()
            assert p.suffix == ".sql"

    def test_creates_subdirectories(self, writer, tmp_path):
        writer.write_all(tmp_path / "ddl")
        assert (tmp_path / "ddl" / "profiles").is_dir()

    def test_idempotent(self, writer, tmp_path):
        out = tmp_path / "ddl"
        writer.write_all(out)
        first = {p.name: p.read_text() for p in out.rglob("*.sql")}
        writer.write_all(out)
        second = {p.name: p.read_text() for p in out.rglob("*.sql")}
        assert first == second
