# Project:   dfe-engine
# File:      Dockerfile
# Purpose:   production container image
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED
#
# The runtime stage below is generated from the hyperi-pylib deployment
# contract (src/dfe_engine/deployment_contract.py). validate_dockerfile in
# tests/unit/test_deployment/test_contract.py guards drift. The builder stage
# is project-specific (uv venv build from the public PyPI index).

# --- Builder stage (uv venv) ---
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS builder

WORKDIR /app

# Manifests + readme first so the install layer caches independently of src.
# README.md is required: pyproject.toml sets readme = "README.md".
COPY pyproject.toml uv.lock README.md ./
COPY src/ src/

RUN uv sync --frozen --no-dev

COPY config/ /app/config/
COPY schemas/ /app/schemas/
RUN chown -R 1000:1000 /app/config

# --- Runtime stage (generated by hyperi-pylib deployment contract) ---
FROM python:3.12-slim AS runtime

# Static OCI labels (from contract)
LABEL org.opencontainers.image.title="dfe-engine"
LABEL org.opencontainers.image.description="DFE Engine -- REST API and config control plane"
LABEL org.opencontainers.image.vendor="HYPERI PTY LIMITED"
LABEL org.opencontainers.image.licenses="BUSL-1.1"
LABEL io.hyperi.profile="production"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl netcat-openbsd iputils-ping \
    && rm -rf /var/lib/apt/lists/*
# Dynamic OCI labels (injected by CI at build time)
ARG OCI_SOURCE=""
ARG OCI_REVISION=""
ARG OCI_VERSION=""
ARG OCI_CREATED=""
LABEL org.opencontainers.image.source="${OCI_SOURCE}"
LABEL org.opencontainers.image.revision="${OCI_REVISION}"
LABEL org.opencontainers.image.version="${OCI_VERSION}"
LABEL org.opencontainers.image.created="${OCI_CREATED}"

# Copy the uv-built virtualenv from the builder and put it on PATH.
COPY --from=builder /app /app
ENV PATH="/app/.venv/bin:$PATH"

ENV DFE_CONFIG_DIR=/app/config \
    DFE_SCHEMAS_DIR=/app/schemas

RUN useradd --create-home --uid 1000 appuser
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -sf http://localhost:8000/api/v1/system/health > /dev/null || exit 1

ENTRYPOINT ["dfe-api"]
CMD ["run"]
