"""Tests for Argo CD RBAC policy generation."""

from dfe_engine.helm.argo_rbac import generate_appproject_roles, generate_rbac_csv


class TestGenerateRbacCsv:
    def test_default_policies(self):
        csv = generate_rbac_csv()
        assert "# Generated by DFE Engine" in csv
        assert "role:dfe-admin" in csv
        assert "role:dfe-infra_admin" in csv
        assert "role:dfe-operator" in csv
        assert "role:dfe-viewer" in csv

    def test_admin_gets_wildcard(self):
        csv = generate_rbac_csv()
        assert "p, role:dfe-admin, *, *, dfe/*, allow" in csv

    def test_infra_admin_gets_application_sync(self):
        csv = generate_rbac_csv()
        assert "p, role:dfe-infra_admin, applications, sync, dfe/*, allow" in csv

    def test_operator_gets_sync_not_delete(self):
        csv = generate_rbac_csv()
        assert "p, role:dfe-operator, applications, sync, dfe/*, allow" in csv
        assert "p, role:dfe-operator, applications, delete" not in csv

    def test_viewer_gets_readonly(self):
        csv = generate_rbac_csv()
        assert "p, role:dfe-viewer, applications, get, dfe/*, allow" in csv
        assert "p, role:dfe-viewer, applications, sync" not in csv

    def test_group_bindings(self):
        groups = {
            "guid-admin": ["admin"],
            "guid-ops": ["operator"],
        }
        csv = generate_rbac_csv(group_role_mapping=groups)
        assert "g, guid-admin, role:dfe-admin" in csv
        assert "g, guid-ops, role:dfe-operator" in csv

    def test_custom_project(self):
        csv = generate_rbac_csv(project="myproject")
        assert "myproject/*, allow" in csv
        assert "dfe/*" not in csv

    def test_custom_role_permissions(self):
        custom = {
            "deployer": {"argo:applications:sync", "argo:applications:get"},
        }
        csv = generate_rbac_csv(role_permissions=custom)
        assert "role:dfe-deployer" in csv
        assert "applications, sync" in csv
        assert "applications, get" in csv

    def test_engine_only_actions_skipped(self):
        custom = {
            "data_user": {"config:read", "query:execute"},
        }
        csv = generate_rbac_csv(role_permissions=custom)
        # No argo policies generated for engine-only roles
        assert "role:dfe-data_user" not in csv


class TestGenerateAppprojectRoles:
    def test_returns_list(self):
        roles = generate_appproject_roles()
        assert isinstance(roles, list)
        assert len(roles) > 0

    def test_role_structure(self):
        roles = generate_appproject_roles()
        for role in roles:
            assert "name" in role
            assert "policies" in role
            assert isinstance(role["policies"], list)

    def test_group_bindings_in_roles(self):
        groups = {"guid-infra": ["infra_admin"]}
        roles = generate_appproject_roles(group_role_mapping=groups)
        infra_role = next(r for r in roles if r["name"] == "infra_admin")
        assert "groups" in infra_role
        assert "guid-infra" in infra_role["groups"]

    def test_no_groups_when_unmapped(self):
        roles = generate_appproject_roles()
        for role in roles:
            if "groups" in role:
                assert len(role["groups"]) > 0
