"""Tests for Argo CD RBAC policy generation."""

from dfe_engine.auth.roles import RoleConfig, RoleDefinition
from dfe_engine.helm.argo_rbac import generate_appproject_roles, generate_rbac_csv


def _make_role_config(roles_dict: dict[str, set[str]]) -> RoleConfig:
    """Build a RoleConfig from a plain dict of role_name → permissions."""
    roles = {
        name: RoleDefinition(description=name, permissions=sorted(perms))
        for name, perms in roles_dict.items()
    }
    return RoleConfig(roles=roles)


class TestGenerateRbacCsv:
    def test_default_policies(self):
        csv = generate_rbac_csv()
        assert "# Generated by DFE Engine" in csv
        assert "role:dfe-admin" in csv
        assert "role:dfe-infra_admin" in csv
        assert "role:dfe-infra_viewer" in csv

    def test_admin_gets_wildcard(self):
        csv = generate_rbac_csv()
        assert "p, role:dfe-admin, *, *, dfe/*, allow" in csv

    def test_infra_admin_gets_wildcard(self):
        # infra_admin has "argo:*" — triggers full wildcard policy
        csv = generate_rbac_csv()
        assert "p, role:dfe-infra_admin, *, *, dfe/*, allow" in csv

    def test_infra_viewer_gets_readonly(self):
        csv = generate_rbac_csv()
        assert "p, role:dfe-infra_viewer, applications, get, dfe/*, allow" in csv
        assert "p, role:dfe-infra_viewer, projects, get, dfe/*, allow" in csv
        assert "p, role:dfe-infra_viewer, applications, sync" not in csv

    def test_group_bindings(self):
        groups = {
            "guid-admin": ["admin"],
            "guid-infra": ["infra_admin"],
        }
        csv = generate_rbac_csv(group_role_mapping=groups)
        assert "g, guid-admin, role:dfe-admin" in csv
        assert "g, guid-infra, role:dfe-infra_admin" in csv

    def test_custom_project(self):
        csv = generate_rbac_csv(project="myproject")
        assert "myproject/*, allow" in csv
        assert "dfe/*" not in csv

    def test_custom_role_config(self):
        role_config = _make_role_config(
            {"deployer": {"argo:applications:sync", "argo:applications:get"}}
        )
        csv = generate_rbac_csv(role_config=role_config)
        assert "role:dfe-deployer" in csv
        assert "applications, sync" in csv
        assert "applications, get" in csv

    def test_engine_only_actions_skipped(self):
        role_config = _make_role_config({"data_user": {"config:read", "query:execute"}})
        csv = generate_rbac_csv(role_config=role_config)
        # No argo policies generated for engine-only roles
        assert "role:dfe-data_user" not in csv

    def test_argo_star_permission_produces_wildcard(self):
        # "argo:*" should emit a full wildcard policy, not per-action lines
        role_config = _make_role_config({"platform_admin": {"argo:*"}})
        csv = generate_rbac_csv(role_config=role_config)
        assert "p, role:dfe-platform_admin, *, *, dfe/*, allow" in csv


class TestGenerateAppprojectRoles:
    def test_returns_list(self):
        roles = generate_appproject_roles()
        assert isinstance(roles, list)
        assert len(roles) > 0

    def test_role_structure(self):
        roles = generate_appproject_roles()
        for role in roles:
            assert "name" in role
            assert "policies" in role
            assert isinstance(role["policies"], list)

    def test_group_bindings_in_roles(self):
        groups = {"guid-infra": ["infra_admin"]}
        roles = generate_appproject_roles(group_role_mapping=groups)
        infra_role = next(r for r in roles if r["name"] == "infra_admin")
        assert "groups" in infra_role
        assert "guid-infra" in infra_role["groups"]

    def test_no_groups_when_unmapped(self):
        roles = generate_appproject_roles()
        for role in roles:
            if "groups" in role:
                assert len(role["groups"]) > 0
