"""Unit tests for dfe-engine's deployment contract.

Verifies that :func:`dfe_engine.deployment_contract.engine_deployment_contract`
is well-formed and that pylib's generators emit valid Dockerfile-runtime,
ArgoCD Application, container manifest, and Helm chart artefacts from it.

These tests are the dfe-engine analogue of dfe-loader's
``tests/integration/helm_contract.rs`` + ``tests/integration/deployment.rs``:
they catch drift between the contract and committed artefacts before CI does.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

from dfe_engine.deployment_contract import engine_deployment_contract

PROJECT_ROOT = Path(__file__).resolve().parents[3]


# ---------------------------------------------------------------------------
# Contract well-formedness
# ---------------------------------------------------------------------------


class TestContractWellFormed:
    """The contract instantiates and exposes the expected shape."""

    def test_contract_instantiates(self) -> None:
        contract = engine_deployment_contract()
        assert contract.app_name == "dfe-engine"
        assert contract.binary_name == "dfe-api"
        assert contract.metrics_port == 8000
        assert contract.env_prefix == "DFE"
        assert contract.config_mount_path == "/etc/dfe/config"

    def test_contract_health_paths(self) -> None:
        contract = engine_deployment_contract()
        # Engine uses the API server's health route, not rustlib's /healthz.
        assert contract.health.liveness_path == "/api/v1/system/health"
        assert contract.health.readiness_path == "/api/v1/system/health"
        assert contract.health.metrics_path == "/metrics"

    def test_contract_secrets(self) -> None:
        contract = engine_deployment_contract()
        groups = {g.group_name for g in contract.secrets}
        assert groups == {"clickhouse", "jwt"}
        # ClickHouse password env must use the cascade-flat key with __ separators.
        clickhouse = next(g for g in contract.secrets if g.group_name == "clickhouse")
        assert clickhouse.env_vars[0].env_var == "DFE__CLICKHOUSE__PASSWORD"

    def test_contract_no_keda(self) -> None:
        # dfe-engine is the control plane -- HPA on CPU is sufficient, no KEDA.
        assert engine_deployment_contract().keda is None

    def test_contract_round_trips_through_json(self) -> None:
        """Contract must serialise to JSON and back without losing fidelity."""
        from hyperi_pylib.deployment import DeploymentContract

        original = engine_deployment_contract()
        as_json = original.to_json()
        restored = DeploymentContract.model_validate_json(as_json)
        assert restored.model_dump() == original.model_dump()


# ---------------------------------------------------------------------------
# Generator outputs
# ---------------------------------------------------------------------------


class TestArtefactGeneration:
    """pylib generators emit non-empty, well-formed artefacts."""

    def test_runtime_stage_includes_contract_points(self) -> None:
        from hyperi_pylib.deployment import generate_runtime_stage

        contract = engine_deployment_contract()
        stage = generate_runtime_stage(contract)

        assert f"FROM {contract.base_image}" in stage
        assert "EXPOSE 8000" in stage
        assert "/api/v1/system/health" in stage  # healthcheck path
        assert 'org.opencontainers.image.title="dfe-engine"' in stage

    def test_container_manifest_is_valid_json(self) -> None:
        from hyperi_pylib.deployment import generate_container_manifest

        contract = engine_deployment_contract()
        manifest = json.loads(generate_container_manifest(contract))
        assert manifest["app_name"] == "dfe-engine"
        assert manifest["binary_name"] == "dfe-api"
        assert manifest["expose_ports"] == [contract.metrics_port]
        assert manifest["healthcheck"]["path"] == contract.health.liveness_path
        assert manifest["entrypoint"] == [contract.binary()]
        assert manifest["cmd"] == contract.entrypoint_args

    def test_argocd_application_is_valid_yaml(self) -> None:
        from hyperi_pylib.deployment import (
            ArgocdConfig,
            argocd_repo_url_from_cascade,
            generate_argocd_application,
        )

        contract = engine_deployment_contract()
        argo = ArgocdConfig(repo_url=argocd_repo_url_from_cascade(contract.app_name))
        rendered = generate_argocd_application(contract, argo)

        # Strip the autogenerated comment header before YAML parsing.
        doc = yaml.safe_load(rendered)
        assert doc["apiVersion"] == "argoproj.io/v1alpha1"
        assert doc["kind"] == "Application"
        assert doc["metadata"]["name"] == "dfe-engine"
        assert doc["spec"]["source"]["repoURL"].endswith("/dfe-engine")
        assert doc["spec"]["destination"]["namespace"] == "dfe"
        # Sync policy must be automated with prune + selfHeal for GitOps.
        sync = doc["spec"]["syncPolicy"]
        assert sync["automated"]["prune"] is True
        assert sync["automated"]["selfHeal"] is True

    def test_chart_generation_creates_expected_files(self, tmp_path: Path) -> None:
        from hyperi_pylib.deployment import generate_chart

        contract = engine_deployment_contract()
        generate_chart(contract, tmp_path)

        assert (tmp_path / "Chart.yaml").exists()
        assert (tmp_path / "values.yaml").exists()
        for template in (
            "_helpers.tpl",
            "deployment.yaml",
            "service.yaml",
            "serviceaccount.yaml",
            "secret.yaml",
        ):
            assert (tmp_path / "templates" / template).exists(), f"missing {template}"

    def test_chart_values_reference_correct_image(self, tmp_path: Path) -> None:
        from hyperi_pylib.deployment import generate_chart

        contract = engine_deployment_contract()
        generate_chart(contract, tmp_path)

        values = (tmp_path / "values.yaml").read_text()
        assert f"{contract.image_registry}/{contract.app_name}" in values


# ---------------------------------------------------------------------------
# Drift detection -- committed artefacts must match the contract
# ---------------------------------------------------------------------------


class TestCommittedArtefactDrift:
    """Committed Dockerfile / chart values must stay aligned with the contract.

    These guard against the contract and the deployed artefacts silently
    drifting apart. If you change the contract, regenerate artefacts and
    commit them; if you tweak Dockerfile/chart by hand, update the contract.
    """

    def test_committed_dockerfile_has_contract_health_endpoint(self) -> None:
        dockerfile = (PROJECT_ROOT / "Dockerfile").read_text()
        contract = engine_deployment_contract()
        assert contract.health.liveness_path in dockerfile, (
            "committed Dockerfile healthcheck must use the contract's liveness_path"
        )

    def test_committed_dockerfile_exposes_metrics_port(self) -> None:
        dockerfile = (PROJECT_ROOT / "Dockerfile").read_text()
        contract = engine_deployment_contract()
        assert f"EXPOSE {contract.metrics_port}" in dockerfile

    def test_committed_dockerfile_entrypoint_matches_contract(self) -> None:
        dockerfile = (PROJECT_ROOT / "Dockerfile").read_text()
        contract = engine_deployment_contract()
        assert f'ENTRYPOINT ["{contract.binary()}"]' in dockerfile
        # entrypoint_args render as the CMD list
        for arg in contract.entrypoint_args:
            assert f'"{arg}"' in dockerfile

    def test_committed_chart_app_port_matches_contract(self) -> None:
        chart_values = yaml.safe_load((PROJECT_ROOT / "chart" / "values.yaml").read_text())
        contract = engine_deployment_contract()
        # The committed chart exposes the API on contract.metrics_port.
        assert chart_values["service"]["port"] == contract.metrics_port

    def test_committed_chart_yaml_name_matches_contract(self) -> None:
        chart = yaml.safe_load((PROJECT_ROOT / "chart" / "Chart.yaml").read_text())
        assert chart["name"] == engine_deployment_contract().app_name


# ---------------------------------------------------------------------------
# Round-trip check -- contract output is deterministic
# ---------------------------------------------------------------------------


def test_artefact_generation_is_deterministic(tmp_path: Path) -> None:
    """Generating twice produces byte-identical output."""
    from hyperi_pylib.deployment import (
        ArgocdConfig,
        generate_argocd_application,
        generate_container_manifest,
        generate_runtime_stage,
    )

    contract = engine_deployment_contract()
    argo = ArgocdConfig(repo_url="https://github.com/hyperi-io/dfe-engine")

    pairs = [
        (generate_runtime_stage(contract), generate_runtime_stage(contract)),
        (generate_container_manifest(contract), generate_container_manifest(contract)),
        (
            generate_argocd_application(contract, argo),
            generate_argocd_application(contract, argo),
        ),
    ]
    for first, second in pairs:
        assert first == second
