"""Tests for HuntResultSchema — dynamic hunt output column generation."""

import pytest

from dfe_engine.hunts.hunt_output import (
    HuntResultSchema,
)


class TestHuntResultSchemaInit:
    """Test HuntResultSchema initialization from profile."""

    def test_loads_timeseries_profile(self):
        """Default profile should be timeseries."""
        schema = HuntResultSchema()
        assert schema.profile_name == "timeseries"

    def test_loads_minimal_profile(self):
        """Minimal profile should load without error."""
        schema = HuntResultSchema(profile_name="minimal")
        assert schema.profile_name == "minimal"

    def test_loads_passthrough_profile(self):
        """Passthrough profile should load without error."""
        schema = HuntResultSchema(profile_name="passthrough")
        assert schema.profile_name == "passthrough"

    def test_invalid_profile_raises(self):
        """Non-existent profile should raise."""
        with pytest.raises(Exception):
            HuntResultSchema(profile_name="nonexistent")

    def test_detection_columns_defined(self):
        """Detection columns should include matched_uuid, rule_id, etc."""
        schema = HuntResultSchema()
        names = [dc.name for dc in schema.detection_columns]
        assert "matched_uuid" in names
        assert "rule_id" in names
        assert "rule_name" in names
        assert "source_table" in names
        assert "hunt_name" in names
        assert "severity" in names


class TestInsertColumns:
    """Test INSERT column list generation."""

    def test_includes_common_header_columns(self):
        """Insert columns should include common header fields."""
        schema = HuntResultSchema()
        cols = schema.insert_columns()
        assert "_timestamp" in cols
        assert "_org_id" in cols

    def test_includes_detection_columns(self):
        """Insert columns should include hunt detection fields."""
        schema = HuntResultSchema()
        cols = schema.insert_columns()
        assert "matched_uuid" in cols
        assert "rule_id" in cols
        assert "severity" in cols

    def test_includes_json_when_profile_has_it(self):
        """Timeseries profile has _json — should be in insert columns."""
        schema = HuntResultSchema(profile_name="timeseries")
        cols = schema.insert_columns()
        assert "_json" in cols

    def test_excludes_json_when_disabled(self):
        """JSON copy can be disabled."""
        schema = HuntResultSchema(include_json_copy=False)
        cols = schema.insert_columns()
        assert "_json" not in cols

    def test_excludes_generated_columns(self):
        """_uuid should NOT be in insert columns (it's a DEFAULT)."""
        schema = HuntResultSchema()
        cols = schema.insert_columns()
        # _uuid is generated by ClickHouse, not inserted
        assert "_uuid" not in cols

    def test_excludes_raw_and_tags(self):
        """_raw and _tags should not be copied to hunt results."""
        schema = HuntResultSchema()
        cols = schema.insert_columns()
        assert "_raw" not in cols
        assert "_tags" not in cols

    def test_column_order_header_first(self):
        """Common header columns should come before detection columns."""
        schema = HuntResultSchema()
        cols = schema.insert_columns()
        # Find indices
        ts_idx = cols.index("_timestamp")
        matched_idx = cols.index("matched_uuid")
        assert ts_idx < matched_idx

    def test_minimal_profile_has_json(self):
        """Minimal profile includes _json for structured payload capture."""
        schema = HuntResultSchema(profile_name="minimal", include_json_copy=True)
        cols = schema.insert_columns()
        assert "_json" in cols


class TestSelectExpression:
    """Test SELECT expression generation."""

    def test_produces_valid_expression(self):
        """Select expression should be non-empty string."""
        schema = HuntResultSchema()
        expr = schema.select_expression(
            rule_id="test_rule_01",
            rule_name="Test Rule",
            source_table="windows_audit",
            hunt_name="test_hunt",
            severity="high",
        )
        assert isinstance(expr, str)
        assert len(expr) > 0

    def test_includes_matched_uuid_alias(self):
        """Should alias _uuid AS matched_uuid."""
        schema = HuntResultSchema()
        expr = schema.select_expression(
            rule_id="r1",
            rule_name="Rule 1",
            source_table="src",
            hunt_name="hunt",
            severity="low",
        )
        assert "_uuid AS matched_uuid" in expr

    def test_includes_literal_values(self):
        """Rule metadata should appear as string literals."""
        schema = HuntResultSchema()
        expr = schema.select_expression(
            rule_id="win_priv_esc_01",
            rule_name="Windows Priv Esc",
            source_table="windows_audit",
            hunt_name="win_hunt",
            severity="critical",
        )
        assert "'win_priv_esc_01' AS rule_id" in expr
        assert "'Windows Priv Esc' AS rule_name" in expr
        assert "'critical' AS severity" in expr

    def test_includes_json_column(self):
        """Timeseries profile should include _json in SELECT."""
        schema = HuntResultSchema()
        expr = schema.select_expression(
            rule_id="r",
            rule_name="r",
            source_table="s",
            hunt_name="h",
            severity="low",
        )
        assert "_json" in expr

    def test_escapes_single_quotes(self):
        """Values with single quotes should be escaped."""
        schema = HuntResultSchema()
        expr = schema.select_expression(
            rule_id="it's_a_rule",
            rule_name="Rule",
            source_table="src",
            hunt_name="hunt",
            severity="low",
        )
        assert "'it''s_a_rule' AS rule_id" in expr

    def test_escapes_backslashes_before_quotes(self):
        """A trailing backslash must not escape the literal's closing quote."""
        schema = HuntResultSchema()
        expr = schema.select_expression(
            rule_id="r1",
            rule_name="Analyst's share C:\\Temp\\",
            source_table="src",
            hunt_name="hunt",
            severity="low",
        )
        assert "'Analyst''s share C:\\\\Temp\\\\' AS rule_name" in expr


class TestBuildInsertSelect:
    """Test full INSERT INTO ... SELECT generation."""

    def test_produces_complete_sql(self):
        """Should produce a valid INSERT INTO ... SELECT ... FROM ... WHERE."""
        schema = HuntResultSchema()
        sql = schema.build_insert_select(
            target_db="acme",
            target_table="detection",
            source_db="acme",
            source_table="windows_audit",
            where_clause="process_executable IN ('certutil.exe')",
            rule_id="win_cert_abuse",
            rule_name="Certificate Abuse",
            hunt_name="windows_detection",
            severity="high",
        )
        assert "INSERT INTO `acme`.`detection`" in sql
        assert "FROM `acme`.`windows_audit`" in sql
        assert "{timestamp_condition}" in sql
        assert "process_executable IN ('certutil.exe')" in sql

    def test_insert_columns_match_select(self):
        """Number of insert columns should match select expressions."""
        schema = HuntResultSchema()
        sql = schema.build_insert_select(
            target_db="org",
            target_table="results",
            source_db="org",
            source_table="src",
            where_clause="x = 1",
            rule_id="r1",
            rule_name="Rule",
            hunt_name="hunt",
            severity="low",
        )
        # Extract insert column count from the parenthesized list
        insert_line = next(line for line in sql.split("\n") if line.strip().startswith("("))
        insert_count = insert_line.count(",") + 1
        # Extract select expression count (lines between SELECT and FROM)
        select_lines = []
        in_select = False
        for line in sql.split("\n"):
            if "SELECT" in line:
                in_select = True
                continue
            if "FROM" in line:
                break
            if in_select:
                select_lines.append(line.strip())
        select_expr = " ".join(select_lines)
        # Count top-level commas in select (not inside quotes)
        select_count = select_expr.count(",") + 1
        assert insert_count == select_count

    def test_empty_where_clause(self):
        """Empty WHERE clause should only have timestamp condition."""
        schema = HuntResultSchema()
        sql = schema.build_insert_select(
            target_db="org",
            target_table="results",
            source_db="org",
            source_table="src",
            where_clause="",
            rule_id="r1",
            rule_name="Rule",
            hunt_name="hunt",
            severity="low",
        )
        assert "WHERE {timestamp_condition}" in sql
        # Should not have trailing AND
        assert (
            "AND" not in sql.split("WHERE")[1].strip()
            or sql.split("WHERE")[1].strip() == "{timestamp_condition}"
        )

    def test_custom_timestamp_placeholder(self):
        """Should support custom timestamp placeholder."""
        schema = HuntResultSchema()
        sql = schema.build_insert_select(
            target_db="org",
            target_table="results",
            source_db="org",
            source_table="src",
            where_clause="x = 1",
            rule_id="r1",
            rule_name="Rule",
            hunt_name="hunt",
            severity="low",
            timestamp_placeholder="{{ts_cond}}",
        )
        assert "{{ts_cond}}" in sql


class TestResultTableColumns:
    """Test result table column definitions."""

    def test_returns_column_dicts(self):
        """Should return a list of column definition dicts."""
        schema = HuntResultSchema()
        cols = schema.result_table_columns()
        assert isinstance(cols, list)
        assert all(isinstance(c, dict) for c in cols)

    def test_includes_common_header_and_detection(self):
        """Should include both common header and detection columns."""
        schema = HuntResultSchema()
        cols = schema.result_table_columns()
        names = [c["name"] for c in cols]
        assert "_timestamp" in names
        assert "_org_id" in names
        assert "_uuid" in names
        assert "matched_uuid" in names
        assert "rule_id" in names

    def test_excludes_raw_and_tags(self):
        """_raw and _tags should be excluded from result table."""
        schema = HuntResultSchema()
        cols = schema.result_table_columns()
        names = [c["name"] for c in cols]
        assert "_raw" not in names
        assert "_tags" not in names
