"""Argo CD RBAC policy generator.

Maps DFE engine role->permission definitions to Argo CD argocd-rbac-cm
policy CSV and AppProject role definitions.

Engine roles with ``argo:<resource>:<action>`` permissions are translated
directly to Argo CD Casbin policy lines. Any permission that doesn't
match the ``argo:<resource>:<action>`` format is silently skipped (it's
an engine-only permission). Unknown Argo resource/action combos generate
a warning but are still emitted -- Argo CD will simply ignore policies
it doesn't understand.
"""

from __future__ import annotations

from typing import Any

from scalo.logger import logger

from dfe_engine.auth.engine import ARGO_ACTION_PREFIX
from dfe_engine.auth.roles import RoleConfig


def generate_rbac_csv(
    group_role_mapping: dict[str, list[str]] | None = None,
    role_config: RoleConfig | None = None,
    project: str = "dfe",
    default_policy: str = "role:dfe-viewer",
) -> str:
    """Generate ``argocd-rbac-cm`` ``policy.csv`` content.

    Args:
        group_role_mapping: OIDC group -> DFE role names.
        role_config: Role configuration. Defaults to built-in.
        project: Argo CD project name for policy scoping.
        default_policy: Default Argo CD role for unauthenticated users.

    Returns:
        Multiline string suitable for ``argocd-rbac-cm`` ``policy.csv``.
    """
    config = role_config or RoleConfig.load_builtin()
    groups = group_role_mapping or {}

    lines: list[str] = []
    lines.append(f"# Generated by DFE Engine -- project: {project}")
    lines.append("")

    # Role policies
    for role_name, role_def in sorted(config.roles.items()):
        actions = set(role_def.permissions)
        role_lines = _role_to_policies(role_name, actions, project)
        if role_lines:
            lines.append(f"# {role_name}")
            lines.extend(role_lines)
            lines.append("")

    # Group -> role bindings
    if groups:
        lines.append("# OIDC group bindings")
        for group_id, roles in sorted(groups.items()):
            for role in roles:
                argo_role = f"role:dfe-{role}"
                lines.append(f"g, {group_id}, {argo_role}")
        lines.append("")

    return "\n".join(lines)


def generate_appproject_roles(
    group_role_mapping: dict[str, list[str]] | None = None,
    role_config: RoleConfig | None = None,
    project: str = "dfe",
) -> list[dict[str, Any]]:
    """Generate Argo CD AppProject ``.spec.roles`` structure.

    Args:
        group_role_mapping: OIDC group -> DFE role names.
        role_config: Role configuration. Defaults to built-in.
        project: Argo CD project name.

    Returns:
        List of role dicts for AppProject ``.spec.roles``.
    """
    config = role_config or RoleConfig.load_builtin()
    groups = group_role_mapping or {}

    # Invert group mapping: role -> [groups]
    role_groups: dict[str, list[str]] = {}
    for group_id, roles in groups.items():
        for role in roles:
            role_groups.setdefault(role, []).append(group_id)

    roles_out: list[dict[str, Any]] = []
    for role_name, role_def in sorted(config.roles.items()):
        actions = set(role_def.permissions)
        policies = _role_to_policies(role_name, actions, project)
        if not policies:
            continue
        entry: dict[str, Any] = {
            "name": role_name,
            "policies": policies,
        }
        if role_name in role_groups:
            entry["groups"] = sorted(role_groups[role_name])
        roles_out.append(entry)

    return roles_out


def _role_to_policies(
    role: str,
    actions: set[str],
    project: str,
) -> list[str]:
    """Convert a DFE role's argo: permissions to Casbin policy lines."""
    argo_role = f"role:dfe-{role}"
    lines: list[str] = []

    # Bare wildcard -- full admin
    if "*" in actions:
        lines.append(f"p, {argo_role}, *, *, {project}/*, allow")
        return lines

    # Argo-namespace wildcard (e.g. "argo:*") -- full argo access
    if f"{ARGO_ACTION_PREFIX}*" in actions:
        lines.append(f"p, {argo_role}, *, *, {project}/*, allow")
        return lines

    for action in sorted(actions):
        if not action.startswith(ARGO_ACTION_PREFIX):
            continue

        remainder = action[len(ARGO_ACTION_PREFIX) :]
        parts = remainder.split(":", 1)
        if len(parts) != 2:
            logger.warning(
                "Skipping malformed argo action '%s' for role '%s' "
                "(expected argo:<resource>:<action>)",
                action,
                role,
            )
            continue

        resource, argo_action = parts
        lines.append(f"p, {argo_role}, {resource}, {argo_action}, {project}/*, allow")

    return lines
